video 8 Repaso y solución a los ejercicios
Huesos99/PracticasPhp pull request #7
Opened 2024-08-27 13:13 UTC by Huesos99

2024-08-27 13:44 UTC, fjmn2001 requested changes
👎🏽 @Huesos99 check my comments

2024-08-27 13:44 UTC, fjmn2001 commented on .gitignore
Why are you deleting this file? 🤔

2024-08-27 13:44 UTC, fjmn2001 commented on .idea/.gitignore
Please, add .idea folder on .gitignore file

2024-08-27 17:16 UTC, Huesos99 commented on .idea/.gitignore
listo

2024-08-29 15:47 UTC, fjmn2001 approved these changes
👍🏽 @Huesos99

2024-08-29 15:47 UTC, merged